apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: pagerduty-operator
  name: pagerduty-operator-metrics-service
  namespace: alertojon-io
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: pagerduty-operator
