# permissions for end users to edit pagerduties.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pagerduty-operator-editor-role
rules:
- apiGroups:
  - alertprovider.alertojon.io
  resources:
  - pagerduties
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - alertprovider.alertojon.io
  resources:
  - pagerduties/status
  verbs:
  - get
