# permissions for end users to view pagerduties.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pagerduty-operator-viewer-role
rules:
- apiGroups:
  - alertprovider.alertojon.io
  resources:
  - pagerduties
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - alertprovider.alertojon.io
  resources:
  - pagerduties/status
  verbs:
  - get
