apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pagerduty-operator-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pagerduty-operator-role
subjects:
- kind: ServiceAccount
  name: pagerduty-operator
  namespace: alertojon-io
