name: Make-Install

on:
  pull_request:
    branches:
      - develop
    paths:
      - 'controllers/**'
      - 'api/**/*.go'

jobs:

  make-install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Make manifests
        run: make manifests

      - name: push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update manifests"
